### ISSUE TITLE
Pretrained model for geometric features

### ISSUE THREAD

**Issue by vdvchen** [liuyuan-pal/LMCNet#1]
Hi, thanks for the great work!

I find that the pretrained model are for geometric features+descriptor. Is it possible to share the model for geometric features only?

**Comment by liuyuan-pal** [comment]
Hi, thanks for your interest. I'll update these models this weekend.

**Comment by vdvchen** [comment]
Thanks for the prompt reply.

By the way, I find that some statistics(https://github.com/liuyuan-pal/LMCNet/blob/368a815e2c01fdd801697114236edd4e2cb5f19f/utils/filter_utils.py#L3) are used to normalize the input(both descriptor and geometric feature). I'm wondering how are these statistics obtained.

**Comment by liuyuan-pal** [comment]
I randomly sample some image pairs (about 5000 pairs) and compute these statistics on these sampled pairs.

**Comment by vdvchen** [comment]
I c, thanks for the answer.

**Comment by liuyuan-pal** [comment]
> I c, thanks for the answer.

Hi, I've updated the geometry-only models!
